### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by uemurakaho** [uemurakaho/furima-41120#22]
自身のフリマアプリのURL 
https://furima-41120.onrender.com/

Basic認証のIDとパスワード 
ユーザー名 : admin
パスワード : 2222

出品者用のメールアドレスとパスワード 
email: uemura.kaho.a@gmail.com
password: aaa111

購入者用のメールアドレスとパスワード
email: uemura.kaho.b@gmail.com
password: bbb111

**Comment by AsukaToyoshima** [comment]
フリマアプリのご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
